stages:
    - build
    - test
    - tag

build:
    stage: build
    script: gradle build -x test

test: 
    stage: test
    script: gradle build
    
tag:
    stage: tag
    script:
        - git remote set-url origin git@$CI_SERVER_HOST:$CI_PROJECT_PATH
        - git checkout $CI_COMMIT_REF_NAME
        - gradle tag 
    when: manual
    only: 
        - branches