stages:
    - test
    - deploy
    - tag

test: 
    stage: test
    script: gradle build
    
deploy:
    stage: deploy
    script:
        - git checkout $CI_COMMIT_REF_NAME
        - gradle build install -x test -Dmaven.repo.local=$MVN_REPO
    only:
        - tags
        
tag:
    stage: tag
    script:
        - export
        - echo "Change to $CI_SERVER_HOST $CI_PROJECT_PATH"
        - git clone ssh://git@$CI_SERVER_HOST/$CI_PROJECT_PATH.git _tmp
        - cd _tmp/hemleditor_parent && gradle tag
    when: manual
    only: 
        - branches